#!/system/bin/sh
# execute any postinstall script then kill it
if [ -e /data/firstboot.sh ];
then
   log -p i -t boot "Executing firstboot.sh..";
   logwrapper /system/bin/sh /data/firstboot.sh;
   rm -f /data/firstboot.sh;
fi;

