#!/system/bin/sh
#
# Load any extra modules

MODULES="ipv6"

KVER=`uname -r`
if [ ! -d /system/lib/modules/$KVER ]
then
    exit 0
fi

for i in $MODULES
do
    modprobe $i >/dev/null 2>&1
done

exit 0
