#!/system/bin/sh

L="log -p i -t SELinuxLabel"

# Bail out early if not on a SELinux build
getprop ro.build.selinux | grep -q 1 || exit
if [ ! -f /file_contexts ]; then
  exit
fi

LABELDATA=0
LABELDALVIKCACHE=0

# Test /data
ls -Zd /data/system | grep -q unlabeled
if [ $? -eq 0 ]; then
  $L "userdata is unlabeled, fixing..."
  LABELDATA=1
fi

# Double-check other files under /data
ls -Z /data/misc/wifi/wpa_supplicant.conf | grep -q "wifi_"
if [ $? -eq 1 ]; then
  $L "data is mis-labeled, fixing..."
  LABELDATA=1
fi

ls -Zd /data/dalvik-cache | grep -q unlabeled
if [ $? -eq 0 ]; then
  $L "dalvik-cache is unlabeled, fixing..."
  LABELDALVIKCACHE=1
fi

ls -Zd /cache/dalvik-cache | grep -q unlabeled
if [ $? -eq 0 ]; then
  $L "dalvik-cache is unlabeled, fixing..."
  LABELDALVIKCACHE=1
fi


if [ $LABELDATA = "1" ]; then
  $L "/data relabel starting..."
  restorecon -R /data
  $L "/data relabel complete"
  $L "/cache relabel starting..."
  restorecon -R /cache
  $L "/cache relabel complete"
fi

if [ $LABELDALVIKCACHE = "1" ]; then
  $L "dalvik-cache relabel starting..."
  restorecon -R /data/dalvik-cache
  restorecon -R /cache/dalvik-cache
  $L "dalvik-cache relabel complete"
fi
