#!/system/bin/sh
#
# Load MODULES
sleep 1
insmod /system/lib/modules/msm_rmnet.ko
insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/cifs.ko
insmod /system/lib/modules/nls_utf8.ko
insmod /system/lib/modules/fuse.ko
echo "+++ RMNET / TUN / CIFS  activated +++";
