#!/bin/bash

cd `dirname $0`
mkdir -p proprietary

adb pull /system/app/CarHomeGoogle.apk proprietary
adb pull /system/app/CarHomeLauncher.apk proprietary
adb pull /system/app/Facebook.apk proprietary
adb pull /system/app/GenieWidget.apk proprietary
adb pull /system/app/Gmail.apk proprietary
adb pull /system/app/GoogleBackupTransport.apk proprietary
adb pull /system/app/GoogleCalendarSyncAdapter.apk proprietary
adb pull /system/app/GoogleContactsSyncAdapter.apk proprietary
adb pull /system/app/GoogleFeedback.apk proprietary
adb pull /system/app/GooglePartnerSetup.apk proprietary
adb pull /system/app/GoogleQuickSearchBox.apk proprietary
adb pull /system/app/GoogleServicesFramework.apk proprietary
adb pull /system/app/HtcCopyright.apk proprietary
adb pull /system/app/HtcEmailPolicy.apk proprietary
adb pull /system/app/HtcSettings.apk proprietary
adb pull /system/app/LatinImeGoogle.apk proprietary
adb pull /system/app/LatinImeTutorial.apk proprietary
adb pull /system/app/Maps.apk proprietary
adb pull /system/app/MarketUpdater.apk proprietary
adb pull /system/app/MediaUploader.apk proprietary
adb pull /system/app/NetworkLocation.apk proprietary
adb pull /system/app/OneTimeInitializer.apk proprietary
adb pull /system/app/PassionQuickOffice.apk proprietary
adb pull /system/app/SetupWizard.apk proprietary
adb pull /system/app/Street.apk proprietary
adb pull /system/app/Talk.apk proprietary
adb pull /system/app/Twitter.apk proprietary
adb pull /system/app/Vending.apk proprietary
adb pull /system/app/VoiceSearch.apk proprietary
adb pull /system/app/YouTube.apk proprietary
adb pull /system/app/googlevoice.apk proprietary
adb pull /system/app/kickback.apk proprietary
adb pull /system/app/soundback.apk proprietary
adb pull /system/app/talkback.apk proprietary
adb pull /system/etc/permissions/com.google.android.maps.xml proprietary
adb pull /system/etc/permissions/features.xml proprietary
adb pull /system/framework/com.google.android.maps.jar proprietary
adb pull /system/lib/libspeech.so proprietary

