add_lunch_combo cyanogen_passion-eng
add_lunch_combo cyanogen_inc-eng
add_lunch_combo cyanogen_hero-eng
add_lunch_combo cyanogen_heroc-eng
add_lunch_combo cyanogen_sholes-eng
add_lunch_combo cyanogen_dream_sapphire-eng
add_lunch_combo cyanogen_bravo-eng
add_lunch_combo cyanogen_bravoc-eng
add_lunch_combo cyanogen_espresso-eng
add_lunch_combo cyanogen_supersonic-eng
add_lunch_combo cyanogen_liberty-eng
add_lunch_combo cyanogen_vibrant-eng
add_lunch_combo cyanogen_legend-eng
add_lunch_combo cyanogen_vision-eng

PATH=$PATH:$PWD/vendor/cyanogen/tools ; export PATH
