add_lunch_combo cyanogen_passion-eng
add_lunch_combo cyanogen_passion-userdebug
add_lunch_combo cyanogen_incredible-eng
add_lunch_combo cyanogen_incredible-userdebug
add_lunch_combo cyanogen_heroc-eng
add_lunch_combo cyanogen_heroc-userdebug
