add_lunch_combo cyanogen_passion-eng
add_lunch_combo cyanogen_inc-eng
add_lunch_combo cyanogen_hero-eng
add_lunch_combo cyanogen_heroc-eng
add_lunch_combo cyanogen_sholes-eng
add_lunch_combo cyanogen_dream_sapphire-eng
add_lunch_combo cyanogen_bravo-eng
add_lunch_combo cyanogen_espresso-eng
