name: "RELEASE_PIXEL_BROADCAST_ENABLED"
namespace: "android_UNKNOWN"
description: "feature flag to enable broadcast feature for Pixel leading phone"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
