
ifeq ($(TARGET_SOC), exynos8895)
TARGET_SLSI_VARIANT := google
BOARD_LIBACRYL_DEFAULT_COMPOSITOR := fimg2d_9810
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_9810
BOARD_LIBACRYL_DEFAULT_BLTER := fimg2d_9810_blter
BOARD_USES_EXYNOS_GRALLOC_VERSION := 1
BOARD_USES_SCALER_M2M1SHOT := true
endif

ifeq ($(TARGET_SOC), exynos9810)
TARGET_SLSI_VARIANT := google
BOARD_LIBACRYL_DEFAULT_COMPOSITOR := fimg2d_8895
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_9810
BOARD_LIBACRYL_DEFAULT_BLTER := fimg2d_8895
BOARD_USES_EXYNOS_GRALLOC_VERSION := 3
BOARD_USES_SCALER_M2M1SHOT := true
endif
