# SPDX-FileCopyrightText: 2023 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

ifeq ($(PRODUCT_VIRTUAL_AB_OTA),true)
BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE ?= true
endif

ifneq ($(WITH_GMS),true)
BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT ?= -1

ifeq ($(BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE),true)
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 450000000
else # PRODUCT_IS_ATV
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 1188036608
endif # PRODUCT_IS_ATV
else # BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 470000000
else # PRODUCT_IS_ATV
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 1957691392
endif # PRODUCT_IS_ATV
endif # BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE

BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT ?= -1
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 40000000
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 27000000
else # PRODUCT_IS_ATV
BOARD_SYSTEM_EXTIMAGE_EXTFS_INODE_COUNT ?= -1
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
endif # PRODUCT_IS_ATV

endif # WITH_GMS
