
ifeq ($(TARGET_SOC), exynos9810)
TARGET_SLSI_VARIANT := google
BOARD_LIBACRYL_DEFAULT_COMPOSITOR := fimg2d_9810
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_9810
BOARD_LIBACRYL_DEFAULT_BLTER := fimg2d_9810_blter
BOARD_USES_EXYNOS_GRALLOC_VERSION := 3
endif
