PATH_OVERRIDE_SOONG := $(shell echo $(TOOLS_PATH_OVERRIDE))

# Add variables that we wish to make available to soong here.
EXPORT_TO_SOONG := \
    KERNEL_ARCH \
    KERNEL_BUILD_OUT_PREFIX \
    KERNEL_CROSS_COMPILE \
    KERNEL_MAKE_CMD \
    KERNEL_MAKE_FLAGS \
    PATH_OVERRIDE_SOONG \
    TARGET_KERNEL_CONFIG \
    TARGET_KERNEL_SOURCE

# Setup SOONG_CONFIG_* vars to export the vars listed above.
# Documentation here:
# https://github.com/LineageOS/android_build_soong/commit/8328367c44085b948c003116c0ed74a047237a69

SOONG_CONFIG_NAMESPACES += lineageVarsPlugin

SOONG_CONFIG_lineageVarsPlugin :=

define addVar
  SOONG_CONFIG_lineageVarsPlugin += $(1)
  SOONG_CONFIG_lineageVarsPlugin_$(1) := $$(subst ",\",$$($1))
endef

$(foreach v,$(EXPORT_TO_SOONG),$(eval $(call addVar,$(v))))

SOONG_CONFIG_NAMESPACES += LINEAGE
SOONG_CONFIG_LINEAGE += \
    ADDITIONAL_GRALLOC_10_USAGE_BITS \
    BOOTLOADER_MESSAGE_OFFSET \
    HAS_LEGACY_CAMERA_HAL1 \
    IGNORES_FTP_PPTP_CONNTRACK_FAILURE \
    NEEDS_NETD_DIRECT_CONNECT_RULE \
    QCOM_SOONG_NAMESPACE \
    RECOVERY_SKIP_EV_REL_INPUT \
    SHOULD_WAIT_FOR_QSEE \
    SUPPORTS_EXTENDED_COMPRESS_FORMAT \
    TARGET_INIT_VENDOR_LIB \
    TARGET_LD_SHIM_LIBS \
    TARGET_SURFACEFLINGER_FOD_LIB \
    USES_CAMERA_PARAMETER_LIBRARY \
    USES_PRE_UPLINK_FEATURES_NETMGRD \
    USES_QCOM_BSP_LEGACY \
    USES_QTI_CAMERA_DEVICE

SOONG_CONFIG_LINEAGE_ADDITIONAL_GRALLOC_10_USAGE_BITS := $(TARGET_ADDITIONAL_GRALLOC_10_USAGE_BITS)
SOONG_CONFIG_LINEAGE_BOOTLOADER_MESSAGE_OFFSET := $(BOOTLOADER_MESSAGE_OFFSET)
SOONG_CONFIG_LINEAGE_HAS_LEGACY_CAMERA_HAL1 := $(TARGET_HAS_LEGACY_CAMERA_HAL1)
SOONG_CONFIG_LINEAGE_IGNORES_FTP_PPTP_CONNTRACK_FAILURE := $(TARGET_IGNORES_FTP_PPTP_CONNTRACK_FAILURE)
SOONG_CONFIG_LINEAGE_NEEDS_NETD_DIRECT_CONNECT_RULE := $(TARGET_NEEDS_NETD_DIRECT_CONNECT_RULE)
SOONG_CONFIG_LINEAGE_QCOM_SOONG_NAMESPACE := $(QCOM_SOONG_NAMESPACE)
SOONG_CONFIG_LINEAGE_RECOVERY_SKIP_EV_REL_INPUT := $(TARGET_RECOVERY_SKIP_EV_REL_INPUT)
SOONG_CONFIG_LINEAGE_SHOULD_WAIT_FOR_QSEE := $(TARGET_KEYMASTER_WAIT_FOR_QSEE)
SOONG_CONFIG_LINEAGE_SUPPORTS_EXTENDED_COMPRESS_FORMAT := $(AUDIO_FEATURE_ENABLED_EXTENDED_COMPRESS_FORMAT)
SOONG_CONFIG_LINEAGE_TARGET_INIT_VENDOR_LIB := $(TARGET_INIT_VENDOR_LIB)
SOONG_CONFIG_LINEAGE_TARGET_LD_SHIM_LIBS := $(TARGET_LD_SHIM_LIBS)
SOONG_CONFIG_LINEAGE_TARGET_SURFACEFLINGER_FOD_LIB := $(TARGET_SURFACEFLINGER_FOD_LIB)
SOONG_CONFIG_LINEAGE_USES_QCOM_BSP_LEGACY := $(TARGET_USES_QCOM_BSP_LEGACY)
SOONG_CONFIG_LINEAGE_USES_QTI_CAMERA_DEVICE := $(TARGET_USES_QTI_CAMERA_DEVICE)
SOONG_CONFIG_LINEAGE_USES_PRE_UPLINK_FEATURES_NETMGRD  := $(TARGET_USES_PRE_UPLINK_FEATURES_NETMGRD)

TARGET_SPECIFIC_CAMERA_PARAMETER_LIBRARY ?= libcamera_parameters
SOONG_CONFIG_LINEAGE_USES_CAMERA_PARAMETER_LIBRARY += $(TARGET_SPECIFIC_CAMERA_PARAMETER_LIBRARY)
