PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/cyanogen_ace.mk \
    $(LOCAL_DIR)/cyanogen_blade.mk \
    $(LOCAL_DIR)/cyanogen_bravo.mk \
    $(LOCAL_DIR)/cyanogen_bravoc.mk \
    $(LOCAL_DIR)/cyanogen_buzz.mk \
    $(LOCAL_DIR)/cyanogen_captivatemtd.mk \
    $(LOCAL_DIR)/cyanogen_click.mk \
    $(LOCAL_DIR)/cyanogen_crespo.mk \
    $(LOCAL_DIR)/cyanogen_crespo4g.mk \
    $(LOCAL_DIR)/cyanogen_desirec.mk \
    $(LOCAL_DIR)/cyanogen_dream_sapphire.mk \
    $(LOCAL_DIR)/cyanogen_encore.mk \
    $(LOCAL_DIR)/cyanogen_espresso.mk \
    $(LOCAL_DIR)/cyanogen_hero.mk \
    $(LOCAL_DIR)/cyanogen_heroc.mk \
    $(LOCAL_DIR)/cyanogen_inc.mk \
    $(LOCAL_DIR)/cyanogen_galaxysmtd.mk \
    $(LOCAL_DIR)/cyanogen_generic.mk \
    $(LOCAL_DIR)/cyanogen_glacier.mk \
    $(LOCAL_DIR)/cyanogen_harmony.mk \
    $(LOCAL_DIR)/cyanogen_legend.mk \
    $(LOCAL_DIR)/cyanogen_leo.mk \
    $(LOCAL_DIR)/cyanogen_liberty.mk \
    $(LOCAL_DIR)/cyanogen_mecha.mk \
    $(LOCAL_DIR)/cyanogen_one.mk \
    $(LOCAL_DIR)/cyanogen_p990.mk \
    $(LOCAL_DIR)/cyanogen_p999.mk \
    $(LOCAL_DIR)/cyanogen_passion.mk \
    $(LOCAL_DIR)/cyanogen_sholes.mk \
    $(LOCAL_DIR)/cyanogen_speedy.mk \
    $(LOCAL_DIR)/cyanogen_supersonic.mk \
    $(LOCAL_DIR)/cyanogen_u8220.mk \
    $(LOCAL_DIR)/cyanogen_vega.mk \
    $(LOCAL_DIR)/cyanogen_vibrantmtd.mk \
    $(LOCAL_DIR)/cyanogen_vision.mk \
    $(LOCAL_DIR)/cyanogen_z71.mk \
    $(LOCAL_DIR)/cyanogen_zeppelin.mk \
    $(LOCAL_DIR)/cyanogen_zero.mk
