PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/cyanogen_ace.mk \
    $(LOCAL_DIR)/cyanogen_anzu.mk \
    $(LOCAL_DIR)/cyanogen_blade.mk \
    $(LOCAL_DIR)/cyanogen_bravo.mk \
    $(LOCAL_DIR)/cyanogen_bravoc.mk \
    $(LOCAL_DIR)/cyanogen_buzz.mk \
    $(LOCAL_DIR)/cyanogen_captivatemtd.mk \
    $(LOCAL_DIR)/cyanogen_click.mk \
    $(LOCAL_DIR)/cyanogen_crespo.mk \
    $(LOCAL_DIR)/cyanogen_crespo4g.mk \
    $(LOCAL_DIR)/cyanogen_desirec.mk \
    $(LOCAL_DIR)/cyanogen_dream_sapphire.mk \
    $(LOCAL_DIR)/cyanogen_droid2.mk \
    $(LOCAL_DIR)/cyanogen_droid2we.mk \
    $(LOCAL_DIR)/cyanogen_encore.mk \
    $(LOCAL_DIR)/cyanogen_espresso.mk \
    $(LOCAL_DIR)/cyanogen_es209ra.mk \
    $(LOCAL_DIR)/cyanogen_fascinatemtd.mk \
    $(LOCAL_DIR)/cyanogen_hallon.mk \
    $(LOCAL_DIR)/cyanogen_hero.mk \
    $(LOCAL_DIR)/cyanogen_heroc.mk \
    $(LOCAL_DIR)/cyanogen_inc.mk \
    $(LOCAL_DIR)/cyanogen_jordan.mk \
    $(LOCAL_DIR)/cyanogen_galaxys2.mk \
    $(LOCAL_DIR)/cyanogen_galaxys2att.mk \
    $(LOCAL_DIR)/cyanogen_galaxysmtd.mk \
    $(LOCAL_DIR)/cyanogen_generic.mk \
    $(LOCAL_DIR)/cyanogen_glacier.mk \
    $(LOCAL_DIR)/cyanogen_legend.mk \
    $(LOCAL_DIR)/cyanogen_leo.mk \
    $(LOCAL_DIR)/cyanogen_liberty.mk \
    $(LOCAL_DIR)/cyanogen_mango.mk \
    $(LOCAL_DIR)/cyanogen_mecha.mk \
    $(LOCAL_DIR)/cyanogen_mesmerizemtd.mk \
    $(LOCAL_DIR)/cyanogen_mimmi.mk \
    $(LOCAL_DIR)/cyanogen_morrison.mk \
    $(LOCAL_DIR)/cyanogen_motus.mk \
    $(LOCAL_DIR)/cyanogen_one.mk \
    $(LOCAL_DIR)/cyanogen_olympus.mk \
    $(LOCAL_DIR)/cyanogen_p990.mk \
    $(LOCAL_DIR)/cyanogen_p999.mk \
    $(LOCAL_DIR)/cyanogen_passion.mk \
    $(LOCAL_DIR)/cyanogen_robyn.mk \
    $(LOCAL_DIR)/cyanogen_saga.mk \
    $(LOCAL_DIR)/cyanogen_shadow.mk \
    $(LOCAL_DIR)/cyanogen_shakira.mk \
    $(LOCAL_DIR)/cyanogen_sholes.mk \
    $(LOCAL_DIR)/cyanogen_showcasemtd.mk \
    $(LOCAL_DIR)/cyanogen_smb_a1002.mk \
    $(LOCAL_DIR)/cyanogen_smb_a1004.mk \
    $(LOCAL_DIR)/cyanogen_smb_a1011.mk \
    $(LOCAL_DIR)/cyanogen_smb_b9701.mk \
    $(LOCAL_DIR)/cyanogen_smultron.mk \
    $(LOCAL_DIR)/cyanogen_speedy.mk \
    $(LOCAL_DIR)/cyanogen_supersonic.mk \
    $(LOCAL_DIR)/cyanogen_v9.mk \
    $(LOCAL_DIR)/cyanogen_u8220.mk \
    $(LOCAL_DIR)/cyanogen_urushi.mk \
    $(LOCAL_DIR)/cyanogen_vega.mk \
    $(LOCAL_DIR)/cyanogen_vibrantmtd.mk \
    $(LOCAL_DIR)/cyanogen_vision.mk \
    $(LOCAL_DIR)/cyanogen_vivo.mk \
    $(LOCAL_DIR)/cyanogen_vivow.mk \
    $(LOCAL_DIR)/cyanogen_z71.mk \
    $(LOCAL_DIR)/cyanogen_zeppelin.mk \
    $(LOCAL_DIR)/cyanogen_zero.mk \
    $(LOCAL_DIR)/cyanogen_zeus.mk \
    $(LOCAL_DIR)/cyanogen_zeusc.mk
