default_containers: "product"
default_containers: "system"
default_containers: "system_ext"
default_containers: "vendor"

release_config {
    name: "ap3a"
    flag_value_files: "release_configs/ap3a.textproto"
}

build_config {
    name: "ap3a"
    flag_value_files: "build_config/ap3a.textproto"
}
