#!/bin/bash

export LOC="$PWD/out/target/product/leo"

mkdir -p "$LOC"/temp

cd "$LOC"/temp
echo "extract update.zip"
unzip -o -qq  "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

echo "Making Leo Compatible Update script"
cd "$LOC"
cd "$LOC"/temp/META-INF/com/google/android
echo 'mount("yaffs2", "MTD", "boot", "/boot");' >> temp
echo 'package_extract_dir("boot", "/boot");' >> temp
grep -vw assert  updater-script >> temp
rm -rf updater-script
grep -vw boot.img  temp > updater-script
rm -rf temp
echo Zipping Package
cd "$LOC"/temp
rm -rf "$LOC"/temp/boot.img
rm -rf "$LOC"/temp/boot
cp -a "$LOC"/boot "$LOC"/temp/boot
rm -rf "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
zip -9yr "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip * > /dev/null
cd "$LOC"

echo Cleanup...
rm -rf "$LOC"/temp

echo done
